CONNECT my_user/my_password@FREEPDB1;


-- Beneficiários
CREATE TABLE BENEFICIARIO (
    ID NUMBER PRIMARY KEY,
    NOME VARCHAR2(100),
    CPF VARCHAR2(14),
    DATA_NASCIMENTO DATE,
    PLANO VARCHAR2(50),
    ATIVO CHAR(1)
);

-- Dependentes
CREATE TABLE DEPENDENTE (
    ID NUMBER PRIMARY KEY,
    BENEFICIARIO_ID NUMBER REFERENCES BENEFICIARIO(ID),
    NOME VARCHAR2(100),
    PARENTESCO VARCHAR2(50),
    DATA_NASCIMENTO DATE
);

-- Procedimentos
CREATE TABLE PROCEDIMENTO (
    ID NUMBER PRIMARY KEY,
    NOME VARCHAR2(100),
    CUSTO NUMBER(10,2),
    TIPO VARCHAR2(50),
    COBERTO_PLANO CHAR(1)
);

-- Autorizações
CREATE TABLE AUTORIZACAO (
    ID NUMBER PRIMARY KEY,
    BENEFICIARIO_ID NUMBER REFERENCES BENEFICIARIO(ID),
    PROCEDIMENTO_ID NUMBER REFERENCES PROCEDIMENTO(ID),
    DATA_SOLICITACAO DATE,
    DATA_RESPOSTA DATE,
    STATUS VARCHAR2(20),
    VALOR_APROVADO NUMBER(10,2)
);

-- Log de Autorizações
CREATE TABLE LOG_AUTORIZACAO (
    ID NUMBER PRIMARY KEY,
    AUTORIZACAO_ID NUMBER REFERENCES AUTORIZACAO(ID),
    DATA_EVENTO TIMESTAMP,
    EVENTO VARCHAR2(100),
    USUARIO VARCHAR2(50)
);

-- Histórico de atendimentos (opcional)
CREATE TABLE HISTORICO_ATENDIMENTO (
    ID NUMBER PRIMARY KEY,
    BENEFICIARIO_ID NUMBER REFERENCES BENEFICIARIO(ID),
    PROCEDIMENTO_ID NUMBER REFERENCES PROCEDIMENTO(ID),
    DATA_ATENDIMENTO DATE,
    STATUS VARCHAR2(20),
    OBSERVACAO VARCHAR2(200)
);

COMMIT;
-- Criação das tabelas para o sistema de autorização de procedimentos médicos