DECLARE
    saida VARCHAR2(200);
BEGIN
    -- CORRETO
    SELECT NOME INTO saida FROM BENEFICIARIO WHERE ID = 1;
    -- ERRADO
    SELECT NOME_BENEFICIARIO INTO saida FROM BENEFICIARIO WHERE ID = 1;
    DBMS_OUTPUT.PUT_LINE('saida: '||saida);
END;
/